# Configuración de la Base de Datos
database:
  host: DB_HOST_DEV
  port: DB_PORT_DEV
  user: DB_USER_DEV
  password: DB_PASSWORD_DEV
  name: DB_NAME_DEV
  ssl_mode: disable

# Configuración del Servidor/API
server:
  port: APP_PORT_DEV
  host: APP_HOST_DEV

# Configuración de Seguridad
#security:
#  jwt_secret: mysupersecretkey
#  jwt_expiration: 3600  # en segundos, por ejemplo 1 hora
#  cors_allowed_origins:
#    - https://frontend.example.com
#    - https://anotherdomain.com
