# ./backend/docker-compose-dev.yml
version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./config/.env.testing
    networks:
      - gestionFct

networks:
  gestionFct:
    name: gestionFct
    driver: bridge