version: '3'

services:
  postgres-production:
    image: 'postgres:latest'
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdataProduction:/var/lib/postgresql/data/

volumes:
  pgdataProduction: